<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fta_domain_model" nsURI="http://www.example.org/fta_domain_model"
    nsPrefix="fta_domain_model">
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eAnnotations source="teamConstraint">
      <details key="teamSizeConstraint" value="self.players->size() >= 2"/>
      <details key="teamTotalGoalsConstraint" value="self.players->collect(player | player.playerstatistics.goals)->sum()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teamSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Player" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalGoals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tournament">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tournamentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" ordered="false"
        upperBound="-1" eType="#//Team" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tournamentformat" lowerBound="1"
        eType="#//TournamentFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTeams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brackets" lowerBound="1"
        eType="#//Bracket" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datastorage" lowerBound="1"
        eType="#//DataStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreTeam1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreTeam2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchResult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" lowerBound="2" upperBound="2"
        eType="#//Team" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchrules" lowerBound="1"
        eType="#//MatchRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//PlayerPosition"
        defaultValueLiteral="MIDFIELDER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playerstatistics" lowerBound="1"
        eType="#//PlayerStatistics"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bracket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bracketSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//UserRole"
        defaultValueLiteral="VIEWER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tournaments" ordered="false"
        upperBound="-1" eType="#//Tournament" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userroles" lowerBound="1"
        eType="#//UserRoles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TournamentFormat" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTeams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minTeams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleElimination" eSuperTypes="#//TournamentFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalsFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoundRobin" eSuperTypes="#//TournamentFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointsForWin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointsForDraw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointsForLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tieBreakerRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleElimination" eSuperTypes="#//TournamentFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasThirdPlacePlayoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchRules" abstract="true">
    <eOperations name="applyRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlayerPosition">
    <eLiterals name="GOALKEEPER"/>
    <eLiterals name="DEFENDER" value="1"/>
    <eLiterals name="MIDFIELDER" value="2"/>
    <eLiterals name="ATTACKER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EClass" name="Standard" eSuperTypes="#//MatchRules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tieBreaking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pentaltyShootouts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtraTime" eSuperTypes="#//MatchRules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTimeDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenaltyShootout" eSuperTypes="#//MatchRules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pentaltyShootouts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupStage" eSuperTypes="#//MatchRules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tieBreaking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserRole">
    <eLiterals name="ADMIN"/>
    <eLiterals name="MANAGER" value="1"/>
    <eLiterals name="VIEWER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRoles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canModifyTournament" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canViewStats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canManageTeams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerStatistics" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assists" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fouls" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yellowCards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redCards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Defender" eSuperTypes="#//PlayerStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cleansheets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goalkeeper" eSuperTypes="#//PlayerStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cleansheets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saves" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStorage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
